name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Clippy
        run: cargo clippy --all

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Rustfmt
        run: cargo +nightly fmt --all -- --check
